language: python
dist: xenial
python: 3.7

install:
  - pip install -r requirements.txt
  - pip install -e .
  - sudo touch /var/log/munkipromoter.log
  - sudo chown travis /var/log/munkipromoter.log

script:
  - coverage run -m pytest tests/*

after_success:
  - python-codacy-coverage -r coverage.xml