language: python
dist: xenial
python: 3.7

install:
  - pip install -r requirements.txt
  - pip install -e .
  - sudo touch /var/log/munkipromoter.log
  - sudo chown travis /var/log/munkipromoter.log

before_script:
  - black --line-length 79 src tests
  - flake8 --ignore E501 src tests

script:
  - coverage run -m pytest tests/* --cov=. --cov-report=xml

after_success:
  - python-codacy-coverage -r coverage.xml