language: python
dist: xenial
python: 3.7

install:
  - pip install -r requirements.txt
  - pip install -e .
  - sudo touch /var/log/munkipromoter.log
  - sudo chown travis /var/log/munkipromoter.log

script:
  - coverage run -m pytest tests/* --cov=. --cov-report=xml

after_success:
  - python-codacy-coverage -r coverage.xml
  - cd docs
  - make html


deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  repo: tcinbis/munkipromoter-docs
  target-branch: master
  local_dir: docs/source/html
  on:
    branch: master
